version: "3"

services:
  thermo-adapter:
    restart: always
    build: ./containers/thermo-adapter
    volumes:
      - thermo-storage:/var/log/thermo
      - /sys/bus/w1/devices/:/sys/bus/w1/devices/
  telegraf:
    restart: always
    # Pin to 1.14 - tailing log file doesn't work on 1.15
    image: telegraf:1.14
    depends_on:
      - influxdb
      - thermo-adapter
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
      - thermo-storage:/var/log/thermo
  influxdb:
    restart: always
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./config/influxdb:/docker-entrypoint-initdb.d
  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s

volumes:
  grafana-storage:
  influxdb-storage:
  thermo-storage:
  portainer_data:

